import { ClubMetadata } from '@/types/config';

export const twitterHandles = [
  'nufc',
  'lfc',
  'arsenal',
  'chelseafc',
  'mancity',
  'manutd',
  'spursofficial',
  'westham',
  'everton',
  'watfordfc',
  'wolves',
  'officialbhafc',
  'norwichcityfc',
  'southamptonfc',
  'cpfc',
  'lufc',
  'brentfordfc',
  'lcfc',
  'avfcofficial',
  'burnleyofficial',
];

export const metadata: ClubMetadata[] = [
  {
    id: 1,
    name: 'Manchester United',
    twitter: {
      id: 558797310,
      name: 'ManUtd',
    },
    colours: {
      primary: '#C70101',
      secondary: '#1A1A1A',
      text: '#000000',
    },
    apisports: { id: 33 },
    reddit: { subreddit: 'reddevils' },
    linkedin: { id: 'manchester-united' },
    instagram: { username: 'manchesterunited' },
    facebook: { id: 'manchesterunited' },
    youtube: { channel: 'UC6yW44UGJJBvYTlfC7CRg2Q' },
  },
  {
    id: 2,
    name: 'Chelsea',
    twitter: {
      id: 22910295,
      name: 'ChelseaFC',
    },
    colours: {
      primary: '#001489',
      secondary: '#FFFFFF',
      text: '#FFFFFF',
    },
    apisports: { id: 49 },
    reddit: { subreddit: 'chelseafc' },
    linkedin: { id: 'chelsea-football-club' },
    instagram: { username: 'chelseafc' },
    facebook: { id: 'chelseafc' },
    youtube: { channel: 'UCU2PacFf99vhb3hNiYDmxww' },
  },
  {
    id: 3,
    name: 'Liverpool',
    twitter: {
      id: 19583545,
      name: 'LFC',
    },
    colours: {
      primary: '#DC0714',
      secondary: '#00634D',
      text: '#000000',
    },
    apisports: { id: 40 },
    reddit: { subreddit: 'liverpoolfc' },
    linkedin: { id: 'liverpool-football-club' },
    instagram: { username: 'liverpoolfc' },
    facebook: { id: 'liverpoolfc' },
    youtube: { channel: 'UC9LQwHZoucFT94I2h6JOcjw' },
  },
  {
    id: 4,
    name: 'Arsenal',
    twitter: {
      id: 34613288,
      name: 'Arsenal',
    },
    colours: {
      primary: '#F00000',
      secondary: '#023474',
      text: '#000000',
    },
    apisports: { id: 42 },
    reddit: { subreddit: 'gunners' },
    linkedin: { id: 'arsenal-f-c' },
    instagram: { username: 'arsenal' },
    facebook: { id: 'arsenal' },
    youtube: { channel: 'UCpryVRk_VDudG8SHXgWcG0w' },
  },
  {
    id: 5,
    name: 'Manchester City',
    twitter: {
      id: 14573900,
      name: 'ManCity',
    },
    colours: {
      primary: '#98C5E9',
      secondary: '#00285E',
      text: '#000000',
    },
    apisports: { id: 50 },
    reddit: { subreddit: 'mcfc' },
    linkedin: { id: 'manchester-city-football-club' },
    instagram: { username: 'mancity' },
    facebook: { id: 'mancity' },
    youtube: { channel: 'UCkzCjdRMrW2vXLx8mvPVLdQ' },
  },
  {
    id: 6,
    name: 'Tottenham Hotspur',
    twitter: {
      id: 121402638,
      name: 'SpursOfficial',
    },
    colours: {
      primary: '#FFFFFF',
      secondary: '#111836',
      text: '#000000',
    },
    apisports: { id: 47 },
    reddit: { subreddit: 'coys' },
    linkedin: { id: 'tottenham-hotspur-ltd' },
    instagram: { username: 'spursofficial' },
    facebook: { id: 'tottenhamhotspur' },
    youtube: { channel: 'UCEg25rdRZXg32iwai6N6l0w' },
  },
  {
    id: 7,
    name: 'Everton',
    twitter: {
      id: 15891449,
      name: 'Everton',
    },
    colours: {
      primary: '#00019E',
      secondary: '#000129',
      text: '#FFFFFF',
    },
    apisports: { id: 45 },
    reddit: { subreddit: 'everton' },
    linkedin: { id: 'everton-football-club' },
    instagram: { username: 'everton' },
    facebook: { id: 'everton' },
    youtube: { channel: 'UCtK4QAczAN2mt2ow_jlGinQ' },
  },
  {
    id: 8,
    name: 'Leicester City',
    twitter: {
      id: 122392884,
      name: 'LCFC',
    },
    colours: {
      primary: '#0B56A4',
      secondary: '#FFFFFF',
      text: '#FFFFFF',
    },
    apisports: { id: 46 },
    reddit: { subreddit: 'lcfc' },
    linkedin: { id: 'leicester-city-football-club' },
    instagram: { username: 'lcfc' },
    facebook: { id: 'lcfc' },
    youtube: { channel: 'UCBkRQtxofyXr09mWtgoUUqw' },
  },
  {
    id: 9,
    name: 'West Ham United',
    twitter: {
      id: 156247074,
      name: 'WestHam',
    },
    colours: {
      primary: '#7D2B3A',
      secondary: '#20AEE7',
      text: '#000000',
    },
    apisports: { id: 48 },
    reddit: { subreddit: 'hammers' },
    linkedin: { id: 'west-ham-united' },
    instagram: { username: 'westham' },
    facebook: { id: 'westham' },
    youtube: { channel: 'UCCNOsmurvpEit9paBOzWtUg' },
  },
  {
    id: 10,
    name: 'Newcastle United',
    twitter: {
      id: 35758259,
      name: 'NUFC',
    },
    colours: {
      primary: '#000000',
      secondary: '#C3A572',
      text: '#FFFFFF',
    },
    apisports: { id: 34 },
    reddit: { subreddit: 'nufc' },
    linkedin: { id: 'newcastle-united-football-club' },
    instagram: { username: 'nufc' },
    facebook: { id: 'newcastleunited' },
    youtube: { channel: 'UCywGl_BPp9QhD0uAcP2HsJw' },
  },
  {
    id: 11,
    name: 'Aston Villa',
    twitter: {
      id: 27489253,
      name: 'AVFCOfficial',
    },
    colours: {
      primary: '#670E36',
      secondary: '#94BEE5',
      text: '#000000',
    },
    apisports: { id: 66 },
    reddit: { subreddit: 'avfc' },
    linkedin: { id: 'aston-villa-football-club' },
    instagram: { username: 'avfcofficial' },
    facebook: { id: 'avfcofficial' },
    youtube: { channel: 'UCICNP0mvtr0prFwGUQIABfQ' },
  },
  {
    id: 12,
    name: 'Southampton',
    twitter: {
      id: 46143892,
      name: 'SouthamptonFC',
    },
    colours: {
      primary: '#D10A11',
      secondary: '#000000',
      text: '#FFFFFF',
    },
    apisports: { id: 41 },
    reddit: { subreddit: 'saintsfc' },
    linkedin: { id: 'southampton-football-club' },
    instagram: { username: 'southamptonfc' },
    facebook: { id: 'southamptonfc' },
    youtube: { channel: 'UCxvXjfiIHQ2O6saVx_ZFqnw' },
  },
  {
    id: 13,
    name: 'Crystal Palace',
    twitter: {
      id: 85307509,
      name: 'CPFC',
    },
    colours: {
      primary: '#004484',
      secondary: '#C51A22',
      text: '#FFFFFF',
    },
    apisports: { id: 52 },
    reddit: { subreddit: 'crystalpalace' },
    linkedin: { id: 'crystal-palace-football-club' },
    instagram: { username: 'cpfc' },
    facebook: { id: 'officialcpfc' },
    youtube: { channel: 'UCWB9N0012fG6bGyj486Qxmg' },
  },
  {
    id: 14,
    name: 'Wolverhampton Wanderers',
    twitter: {
      id: 49296276,
      name: 'Wolves',
    },
    colours: {
      primary: '#FDB913',
      secondary: '#000000',
      text: '#000000',
    },
    apisports: { id: 39 },
    reddit: { subreddit: 'wwfc' },
    linkedin: { id: 'wolverhamptonwanderers' },
    instagram: { username: 'wolves' },
    facebook: { id: 'wolves' },
    youtube: { channel: 'UCQ7Lqg5Czh5djGK6iOG53KQ' },
  },
  {
    id: 15,
    name: 'Leeds United',
    twitter: {
      id: 1024095475,
      name: 'LUFC',
    },
    colours: {
      primary: '#FFFFFF',
      secondary: '#FFD400',
      text: '#000000',
    },
    apisports: { id: 63 },
    reddit: { subreddit: 'leedsunited' },
    linkedin: { id: 'leedsunited' },
    instagram: { username: 'leedsunited' },
    facebook: { id: 'leedsunited' },
    youtube: { channel: 'UCyQcJHDN4uYfPa1DHzKVSnw' },
  },
  {
    id: 16,
    name: 'Watford',
    twitter: {
      id: 226590250,
      name: 'WatfordFC',
    },
    colours: {
      primary: '#FBEE23',
      secondary: '#000000',
      text: '#000000',
    },
    apisports: { id: 38 },
    reddit: { subreddit: 'watford_fc' },
    linkedin: { id: 'watford-football-club' },
    instagram: { username: 'watfordfcofficial' },
    facebook: { id: 'watfordfc' },
    youtube: { channel: 'UCptKljTrbdMTgmuekGKhRug' },
  },
  {
    id: 17,
    name: 'Norwich City',
    twitter: {
      id: 187572312,
      name: 'NorwichCityFC',
    },
    colours: {
      primary: '#FFF200',
      secondary: '#00A651',
      text: '#000000',
    },
    apisports: { id: 71 },
    reddit: { subreddit: 'norwichcity' },
    linkedin: { id: 'norwich-city-football-club' },
    instagram: { username: 'norwichcityfc' },
    facebook: { id: 'norwichcityfootballclub' },
    youtube: { channel: 'UCzdkZv6--BWsUQ9rKUtQ1TQ' },
  },
  {
    id: 18,
    name: 'Brighton & Hove Albion',
    twitter: {
      id: 57606154,
      name: 'OfficialBHAFC',
    },
    colours: {
      primary: '#0054A6',
      secondary: '#FFFFFF',
      text: '#FFFFFF',
    },
    apisports: { id: 51 },
    reddit: { subreddit: 'brightonhovealbion' },
    linkedin: { id: 'brighton-&-hove-albion-fc' },
    instagram: { username: 'officialbhafc' },
    facebook: { id: 'officialbhafc' },
    youtube: { channel: 'UCf-cpC9WAdOsas19JHipukA' },
  },
  {
    id: 19,
    name: 'Brentford',
    twitter: {
      id: 103036163,
      name: 'BrentfordFC',
    },
    colours: {
      primary: '#C61D22',
      secondary: '#FFFFFF',
      text: '#FFFFFF',
    },
    apisports: { id: 55 },
    reddit: { subreddit: 'brentford' },
    linkedin: { id: 'brentford-football-club' },
    instagram: { username: 'brentfordfc' },
    facebook: { id: 'brentfordfootballclub1889' },
    youtube: { channel: 'UCAalMUm3LIf504ItA3rqfug' },
  },
  {
    id: 20,
    name: 'Burnley',
    twitter: {
      id: 441309926,
      name: 'BurnleyOfficial',
    },
    colours: {
      primary: '#81204C',
      secondary: '#8FD2F4',
      text: '#FFFFFF',
    },
    apisports: { id: 44 },
    reddit: { subreddit: 'burnley' },
    linkedin: { id: 'burnleyofficial' },
    instagram: { username: 'burnleyofficial' },
    facebook: { id: 'burnleyofficial' },
    youtube: { channel: 'UChvUXuSDeEFSQZS8GcPMtkg' },
  },
];

export const clubsColours = [
  {
    id: 558797310,
    name: 'ManUtd',
    colour: '#C70101',
    secondaryColour: '#1A1A1A',
    textColour: '#000000',
  },
  {
    id: 22910295,
    name: 'ChelseaFC',
    colour: '#001489',
    secondaryColour: '#FFFFFF',
    textColour: '#FFFFFF',
  },
  {
    id: 19583545,
    name: 'LFC',
    colour: '#DC0714',
    secondaryColour: '#00634D',
    textColour: '#000000',
  },
  {
    id: 34613288,
    name: 'Arsenal',
    colour: '#F00000',
    secondaryColour: '#023474',
    textColour: '#000000',
  },
  {
    id: 14573900,
    name: 'ManCity',
    colour: '#98C5E9',
    secondaryColour: '#00285E',
    textColour: '#000000',
  },
  {
    id: 121402638,
    name: 'SpursOfficial',
    colour: '#FFFFFF',
    secondaryColour: '#111836',
    textColour: '#000000',
  },
  {
    id: 15891449,
    name: 'Everton',
    colour: '#00019E',
    secondaryColour: '#000129',
    textColour: '#FFFFFF',
  },
  {
    id: 122392884,
    name: 'LCFC',
    colour: '#0B56A4',
    secondaryColour: '#FFFFFF',
    textColour: '#FFFFFF',
  },
  {
    id: 156247074,
    name: 'WestHam',
    colour: '#7D2B3A',
    secondaryColour: '#20AEE7',
    textColour: '#000000',
  },
  {
    id: 35758259,
    name: 'NUFC',
    colour: '#000000',
    secondaryColour: '#C3A572',
    textColour: '#FFFFFF',
  },
  {
    id: 27489253,
    name: 'AVFCOfficial',
    colour: '#670E36',
    secondaryColour: '#94BEE5',
    textColour: '#000000',
  },
  {
    id: 46143892,
    name: 'SouthamptonFC',
    colour: '#D10A11',
    secondaryColour: '#000000',
    textColour: '#FFFFFF',
  },
  {
    id: 85307509,
    name: 'CPFC',
    colour: '#004484',
    secondaryColour: '#C51A22',
    textColour: '#FFFFFF',
  },
  {
    id: 49296276,
    name: 'Wolves',
    colour: '#FDB913',
    secondaryColour: '#000000',
    textColour: '#000000',
  },
  {
    id: 1024095475,
    name: 'LUFC',
    colour: '#FFFFFF',
    secondaryColour: '#FFD400',
    textColour: '#000000',
  },
  {
    id: 226590250,
    name: 'WatfordFC',
    colour: '#FBEE23',
    secondaryColour: '#000000',
    textColour: '#000000',
  },
  {
    id: 187572312,
    name: 'NorwichCityFC',
    colour: '#FFF200',
    secondaryColour: '#00A651',
    textColour: '#000000',
  },
  {
    id: 57606154,
    name: 'OfficialBHAFC',
    colour: '#0054A6',
    secondaryColour: '#FFFFFF',
    textColour: '#FFFFFF',
  },
  {
    id: 103036163,
    name: 'BrentfordFC',
    colour: '#C61D22',
    secondaryColour: '#FFFFFF',
    textColour: '#FFFFFF',
  },
  {
    id: 441309926,
    name: 'BurnleyOfficial',
    colour: '#81204C',
    secondaryColour: '#8FD2F4',
    textColour: '#FFFFFF',
  },
];
